# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: prisma_access_mobile_user_onboarding_v90
# label used for menu selection
label: Step 3 - Prisma Access Mobile User Onboarding v90
description: Prisma Access mobile user onboarding

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panorama-gpcs
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Prisma Access

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: portal_hostname
    description: portal subdomain
    default: my-subdomain
    type_hint: text
    help_text: subdomain prefix for cloudservice.com
  - name: deployment_region
    description: regional to use for mobile user configuration
    default: americas
    type_hint: dropdown
    dd_list:
      - key: Americas
        value: americas
    # TODO: add in more dropdown options and link to locations
    help_text: skillet allows for selecting a single starter region. additional regions added in Panorama
    # TODO: figure out how to only show subset of locations AND map to snippets below based on region
  - name: ip_pool_cidr
    description: mobile user IP address pool
    default: 192.168.2.0/23
    type_hint: cidr
    help_text: use a CIDR (/23) address block for pool entry. Only a single pool option with this skillet
  - name: deployment_location
    description: deployment location options for the Americas region
    default: us-east-1
    type_hint: text
    # TODO: create list of locations per region with xml coded naming
    help_text: select Americas locations for mobile user access

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: mobile_user_gateway
    xpath: /config/devices/entry[@name="localhost.localdomain"]/template/entry[@name="Mobile_User_Template"]/config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
      <global-protect>
        <global-protect-gateway>
          <entry name="GlobalProtect_External_Gateway">
            <client-auth>
              <entry name="DEFAULT">
                <authentication-profile>Local-DB</authentication-profile>
                <os>Any</os>
              </entry>
            </client-auth>
            <remote-user-tunnel-configs>
              <entry name="DEFAULT">
                <authentication-override>
                  <accept-cookie>
                    <cookie-lifetime>
                      <lifetime-in-hours>24</lifetime-in-hours>
                    </cookie-lifetime>
                  </accept-cookie>
                  <cookie-encrypt-decrypt-cert>Authentication Cookie Cert</cookie-encrypt-decrypt-cert>
                  <generate-cookie>yes</generate-cookie>
                </authentication-override>
                <source-user>
                  <member>any</member>
                </source-user>
                <os>
                  <member>any</member>
                </os>
              </entry>
            </remote-user-tunnel-configs>
            <tunnel-mode>yes</tunnel-mode>
          </entry>
        </global-protect-gateway>
      </global-protect>

  - name: mobile_user_gateway_tunnel
    xpath: /config/devices/entry[@name="localhost.localdomain"]/template/entry[@name="Mobile_User_Template"]/config/devices/entry[@name="localhost.localdomain"]
    element: |-
      <network>
        <tunnel>
          <global-protect-gateway>
            <entry name="GlobalProtect_External_Gateway-N">
              <local-address>
                <ip/>
              </local-address>
            </entry>
          </global-protect-gateway>
        </tunnel>
      </network>

  - name: mobile_user_portal
    xpath: /config/devices/entry[@name="localhost.localdomain"]/template/entry[@name="Mobile_User_Template"]/config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
      <global-protect>
        <global-protect-portal>
          <entry name="GlobalProtect_Portal">
            <portal-config>
              <local-address>
                <interface>-</interface>
                <ip/>
              </local-address>
              <client-auth>
                <entry name="DEFAULT">
                  <os>Any</os>
                  <authentication-profile>Local-DB</authentication-profile>
                  <authentication-message>Enter login credentials</authentication-message>
                </entry>
              </client-auth>
              <custom-login-page>factory-default</custom-login-page>
              <custom-home-page>factory-default</custom-home-page>
            </portal-config>
            <client-config>
              <configs>
                <entry name="DEFAULT">
                  <gateways>
                    <external>
                      <list>
                        <entry name="GP cloud service">
                          <fqdn>gpcloudservice.com</fqdn>
                          <priority-rule>
                            <entry name="Any">
                              <priority>1</priority>
                            </entry>
                          </priority-rule>
                          <manual>yes</manual>
                        </entry>
                      </list>
                      <cutoff-time>5</cutoff-time>
                    </external>
                  </gateways>
                  <authentication-override>
                    <accept-cookie>
                      <cookie-lifetime>
                        <lifetime-in-hours>24</lifetime-in-hours>
                      </cookie-lifetime>
                    </accept-cookie>
                    <cookie-encrypt-decrypt-cert>Authentication Cookie Cert</cookie-encrypt-decrypt-cert>
                    <generate-cookie>yes</generate-cookie>
                  </authentication-override>
                  <source-user>
                    <member>any</member>
                  </source-user>
                  <os>
                    <member>any</member>
                  </os>
                </entry>
              </configs>
            </client-config>
            <clientless-vpn>
              <hostname>{{ portal_hostname }}.gpcloudservice.com</hostname>
            </clientless-vpn>
          </entry>
        </global-protect-portal>
      </global-protect>

  - name: mobile_users_plugin_configuration
    xpath: /config/devices/entry[@name="localhost.localdomain"]/plugins/cloud_services/mobile-users
    element: |-
      <onboarding>
        <entry name="{{ portal_hostname }}.gpcloudservice.com">
          <portal-hostname>
            <default-domain>
              <hostname>{{ portal_hostname }}</hostname>
            </default-domain>
          </portal-hostname>
          <ip-pools>
            <entry name="{{ deployment_region }}">
              <ip-pool>
                <member>{{ ip_pool_cidr }}</member>
              </ip-pool>
            </entry>
          </ip-pools>
          <dns-servers>
            <entry name="{{ deployment_region }}"/>
          </dns-servers>
          <authentication-profile>Local-DB</authentication-profile>
          <authentication-override-certificate>Authentication Cookie Cert</authentication-override-certificate>
          <global-protect-portal>GlobalProtect_Portal</global-protect-portal>
          <global-protect-gateway>GlobalProtect_External_Gateway</global-protect-gateway>
          <deployment>
            <region>
              <entry name="{{ deployment_region }}">
                <locations>
                  <member>{{ deployment_location }}</member>
                </locations>
              </entry>
            </region>
          </deployment>
          <manual-gateway>
            <region>
              <entry name="{{ deployment_region }}">
                <locations>
                  <member>{{ deployment_location }}</member>
                </locations>
              </entry>
            </region>
          </manual-gateway>
        </entry>
      </onboarding>

# ---------------------------------------------------------------------
# end of snippets section