# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: prisma_access_quick_test
# label used for menu selection
label: Prisma Access Quick Test
description: |-
    Prisma Access initial Panorama configuration for service setup including
    instrastructure subnet, infrastructure BGP AS, template, template-stack, and device-group

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panorama-gpcs
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Prisma Access

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: infra_subnet
    description: Infrastructure Subnet
    default: 192.168.254.0/24
    type_hint: cidr
    help_text: |-
      Specify a RFC-1918 compliant IP address pool (at least a /24 subnet) that does not overlap with other
      IP addresses in your network. These IP addresses will be used by the cloud service.
  - name: infra_bgp_as
    description: Infrastructure BGP AS
    default: 65534
    type_hint: number
    help_text: |-
      Specify a RFC-6996 compliant Private AS number. Accepted formats are 4-Byte AS Plain [64512-65534],
      [4200000000-4294967294] or AS Dot [0.64512-0.65534], [64086.59904-65535.65534] notation.
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: mobile_user_gateway
    xpath: /config/devices/entry[@name="localhost.localdomain"]/template/entry[@name="Mobile_User_Template"]/config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
      <global-protect>
        <global-protect-gateway>
          <entry name="GlobalProtect_External_Gateway">
            <client-auth>
              <entry name="DEFAULT">
                <authentication-profile>Local-DB</authentication-profile>
                <os>Any</os>
              </entry>
            </client-auth>
            <remote-user-tunnel-configs>
              <entry name="DEFAULT">
                <authentication-override>
                  <accept-cookie>
                    <cookie-lifetime>
                      <lifetime-in-hours>24</lifetime-in-hours>
                    </cookie-lifetime>
                  </accept-cookie>
                  <cookie-encrypt-decrypt-cert>Authentication Cookie Cert</cookie-encrypt-decrypt-cert>
                  <generate-cookie>yes</generate-cookie>
                </authentication-override>
                <source-user>
                  <member>any</member>
                </source-user>
                <os>
                  <member>any</member>
                </os>
              </entry>
            </remote-user-tunnel-configs>
            <tunnel-mode>yes</tunnel-mode>
          </entry>
        </global-protect-gateway>
      </global-protect>


# ---------------------------------------------------------------------
# end of snippets section