name: prisma_access_azure_deploy_panorama

label: Prisma Access Deploy Panorama in Azure

description: Deploy Panorama into Azure

type: terraform

labels:
  help_text: Managing Terraform projects in Panhandler
  help_link: https://panhandler.readthedocs.io/en/master/examples/terraform_skillet.html#terraform-state-files
  collection:
    - Kitchen Sink

variables:
  - name: adminUsername
    description: Admin Username
    default: panhandler
    type_hint: text
  - name: adminPassword
    description: Admin Password
    default:
    type_hint: password
    help_text: Password must be at least 11 chars and complex
  - name: hostname
    description: Hostname
    default: prisma-access-controller
    type_hint: text
  - name: virtualMachineRG
    description: Resource Group
    default:
    type_hint: text
    required: True
  - name: Location
    description: Azure Location
    default:
    required: True
    type_hint: text
    help_text: Choose a location near you from https://azure.microsoft.com/en-us/global-infrastructure/locations/
