# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: prisma_access_mobile_full_config_render_v90
# label used for menu selection
label: Prisma Access Mobile Users Full Config File for Import v90
description: |
  Prisma Access Mobile Users setup and onboarding configuration as a loadable config

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: template
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Prisma Access

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: infra_subnet
    description: Infrastructure Subnet
    default: 192.168.254.0/24
    type_hint: cidr
    help_text: |-
      Specify a RFC-1918 compliant IP address pool (at least a /24 subnet) that does not overlap with other
      IP addresses in your network. These IP addresses will be used by the cloud service.
  - name: infra_bgp_as
    description: Infrastructure BGP AS
    default: 65534
    type_hint: number
    help_text: |-
      Specify a RFC-6996 compliant Private AS number. Accepted formats are 4-Byte AS Plain [64512-65534],
      [4200000000-4294967294] or AS Dot [0.64512-0.65534], [64086.59904-65535.65534] notation.
  - name: portal_hostname
    description: portal subdomain
    default: my-subdomain
    type_hint: text
    help_text: subdomain prefix for cloudservice.com
  - name: deployment_region
    description: regional to use for mobile user configuration
    default: americas
    type_hint: dropdown
    dd_list:
      - key: North America & South America
        value: americas
      - key: Africa, Europe & Middle East
        value: europe
      - key: Asia, Australia & Japan
        value: apac
    help_text: skillet allows for selecting a single starter region. additional regions or worldwide added in Panorama GUI
  - name: deployment_locations_americas
    description: deployment locations for North America & South America
    default: us-east-1
    toggle_hint:
      source: deployment_region
      value: americas
    type_hint: checkbox
    cbx_list:
      - key: US East
        value: us-east-1
      - key: US Central
        value: us-east-2
      - key: US Northeast
        value: us-northeast
  - name: deployment_locations_europe
    description: deployment locations for Africa, Europe & Middle East
    default: eu-west-1
    toggle_hint:
      source: deployment_region
      value: europe
    type_hint: checkbox
    cbx_list:
      - key: Germany Central
        value: eu-central-1
      - key: Ireland
        value: eu-west-1
      - key: UK
        value: eu-west-1
  - name: deployment_locations_apac
    description: deployment locations for Asia, Australia & Japan
    default: australia-east
    toggle_hint:
      source: deployment_region
      value: apac
    type_hint: checkbox
    cbx_list:
      - key: Australia East
        value: australia-east
      - key: Australia South
        value: australia-south
      - key: Japan Central
        value: ap-northeast-1
      - key: South Korea
        value: ap-northeast-2
  - name: ip_pool_cidr
    description: mobile user IP address pool
    default: 192.168.2.0/23
    type_hint: cidr
    help_text: use a CIDR (/23) address block for pool entry. Only a single pool option with this skillet

snippets:

  - name: prisma_access_full_config
    file: prisma_access_full_config.conf

# ---------------------------------------------------------------------
# end of snippets section